version: 1.0.{build}
image: Visual Studio 2017

platform: 
 - x86

clone_folder: c:\mgs

build_script:
 - set PATH=C:\cygwin64\bin;%PATH%
 - g++ build\progress_script\symProgress.c -o build\progress_script\progress.exe
 - cd build
 - make multicore-fix
 - make PSYQ_SDK=c:\psyq C_DEPS=false -j4
 - make progress
 
install:
 - git clone https://github.com/FoxdieTeam/psyq_sdk.git c:\psyq --depth 1
 - git submodule update --init --recursive
 - choco install make --source=cygwin

test: off
