version: 1.0.{build}
image: Visual Studio 2017

platform: 
 - x86

clone_folder: c:\mgs

build_script:
 - g++ build\progress\symProgress.c -o build\progress\progress.exe
 - set PATH=C:\cygwin64\bin;%PATH%
 - cd build
 - make PSYQ_SDK=c:\psyq C_DEPS=false -j1
 - make progress
 
install:
 - git clone https://github.com/FoxdieTeam/psyq_sdk.git c:\psyq --depth 1
 - git submodule update --init --recursive
 - choco install make --source=cygwin

test: off
